TarantoWebCatalogo/TarantoWebCatalogo.Web/Controllers/CatalogoController.cs
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.WebPages;
using ClosedXML.Excel;
using log4net;
using Newtonsoft.Json;
using TarantoWebCatalogo.Services.BoletinLanzamiento;
using TarantoWebCatalogo.Services.Core;
using TarantoWebCatalogo.Services.ListaDePrecios;
using TarantoWebCatalogo.Services.Pedidos;
using TarantoWebCatalogo.ViewModels.Pedidos;
using TarantoWebCatalogo.Web.helpers;

namespace TarantoWebCatalogo.Web.Controllers
{
    public partial class CatalogoController : BaseController
    {
        private readonly IPedidosService _pedidosService;
        private readonly ISeguridadService _seguridadService;
        private readonly IListaDePrecioService _listaDePrecioService;
        private readonly IBoletinLanzamientoService _boletinLanzamientoService;
        private static readonly ILog Log = LogManager.GetLogger("LogFileAppender");

        public CatalogoController()
        {
            _pedidosService = Factory.CrearPedidoService();
            var webConfigHelper = new WebConfigHelper();
            _seguridadService = Factory.CrearSeguridadService(webConfigHelper.ApiUrl);
            _listaDePrecioService = Factory.CrearListaDePrecioService();
            _boletinLanzamientoService = Factory.CrearBoletinLanzamientoService();
        }

        public virtual ActionResult Index()
        {

            ViewBag.EsCliente = false;
            if (_seguridadService.HayUsuarioLogueado)
            {
                ViewBag.EsCliente = !_seguridadService.UsuarioLogueadoEsProveedor;
                ViewBag.ApiLocalUrl = System.Web.Configuration.WebConfigurationManager.AppSettings["ApiLocalUrl"];
            }
            ViewBag.ApiUrl = System.Web.Configuration.WebConfigurationManager.AppSettings["ApiUrl"];
            return View();
        }

        public virtual ActionResult ListaDePrecios()
        {
            var listaDePrecios = _listaDePrecioService.ObtenerTodas();
            return View(listaDePrecios);
        }

        public virtual ActionResult BoletinLanzamiento()
        {
            var boletines = _boletinLanzamientoService.ObtenerTodos();
            return View(boletines);
        }

        public virtual ActionResult Ofertas()
        {
            var boletines = _boletinLanzamientoService.ObtenerTodos();
            return View(boletines);
        }


        public virtual ActionResult CarritoDeComprasIndex()
        {
            if (!_seguridadService.UsuarioLogueadoEsProveedor)
            {
                var pedido = _pedidosService.ObtenerPorUsuario(_seguridadService.UsuarioLogueadoCodigo);
                ViewBag.ApiLocalUrl = System.Web.Configuration.WebConfigurationManager.AppSettings["ApiLocalUrl"];
                ViewBag.BaseUrl = System.Web.Configuration.WebConfigurationManager.AppSettings["BaseUrl"];
                return View(pedido);
            }
            return RedirectToAction(MVC.Home.Perfil());
        }

        [ChildActionOnly]
        public virtual ActionResult MostrarProducto()
        {
            var pedido = _pedidosService.ObtenerPorUsuario(_seguridadService.UsuarioLogueadoCodigo);
            return PartialView("_DetallePedido", pedido);
        }
        
        [HttpGet]
        public virtual ActionResult CrearPedido()
        {
            if (_seguridadService.UsuarioLogueadoEsProveedor)
            {
                return RedirectToAction(MVC.Catalogo.Index());
            }
            return View(new PedidoCreate{ Cantidad = 1});
        }

        [HttpPost]
        public virtual ActionResult CrearPedido(PedidoCreate pedido)
        {
            _pedidosService.Agregar(_seguridadService.UsuarioLogueadoCodigo,
                pedido.Articulo, pedido.Descripcion, pedido.Cantidad, pedido.PrecioUnitario, pedido.Stock, false, null);

            return RedirectToAction(MVC.Catalogo.CarritoDeComprasIndex());
        }
        
        public virtual ActionResult EliminarPedido(string articulo, int idPedido)
        {

            _pedidosService.Eliminar(_seguridadService.UsuarioLogueadoCodigo, articulo, idPedido);
            return RedirectToAction(MVC.Catalogo.CarritoDeComprasIndex());
            
        }

        public virtual ActionResult Eliminar(int idPedido)
        {
            _pedidosService.Eliminar(_seguridadService.UsuarioLogueadoCodigo, idPedido);
            return RedirectToAction(MVC.Catalogo.CarritoDeComprasIndex());
        }

        public virtual ActionResult PedidoPorExcel(int processStatus)
        {
            if (!_seguridadService.HayUsuarioLogueado || _seguridadService.UsuarioLogueadoEsProveedor)
            {
                return RedirectToAction(MVC.Catalogo.Index());
            }

            ViewBag.ProcessStatus = processStatus;

            return View();
        }

        public virtual ActionResult Pedidos()
        {
            if (!_seguridadService.HayUsuarioLogueado)
            {
                return RedirectToAction(MVC.Home.Perfil());
            }

            var pedido = _pedidosService.ObtenerPedidosProcesadosPorUsuario(_seguridadService.UsuarioLogueadoCodigo);
            return View(pedido);
        }

        public virtual ActionResult PedidoDetalleArticulos(int idPedido, string fecha, string observacion, string origen, int idOracle)
        {
            var pedido = _pedidosService.ObtenerDetallePedidosProcesadosPorIdPedido(idPedido);
            ViewBag.Fecha = fecha;
            ViewBag.Observacion = observacion;
            ViewBag.Origen = origen;
            ViewBag.IdOracle = idOracle;
            return View(pedido);
        }

        [HttpPost]
        public virtual ActionResult PedidoPorExcel(HttpPostedFileBase archivoExcel)
        {
             if (ValidarPedidoExcel(archivoExcel, out var actionResult)) return actionResult;

            const string mensaje = "El archivo seleccionado no es un archivo de Excel válido.";

            ViewBag.Mensaje = mensaje;
            return View();
        }

        private bool ValidarPedidoExcel(HttpPostedFileBase archivoExcel, out ActionResult actionResult)
        {
            if (archivoExcel?.FileName == null)
            {
                ViewBag.Mensaje = "Debe seleccionar un archivo de tipo Excel";
                {
                    actionResult = View();
                    return true;
                }
            }

            if (archivoExcel.FileName.EndsWith("xlsx"))
            {
                string mensaje = null;
                try
                {
                    using (var workBook = new XLWorkbook(archivoExcel.InputStream))
                    {
                        var workSheet = workBook.Worksheet(1);
                        var dt = new DataTable();
                        var firstRow = true;
                        if (workSheet.Rows().Count() > 70) //Tope elegido por el cliente
                        {
                            mensaje = "El Excel seleccionado no debe superar las 70 líneas";
                        }
                        else if (!workSheet.Rows().Any())
                        {
                            mensaje = "El Excel seleccionado esta vacío";
                        }
                        else
                        {

                            foreach (var row in workSheet.Rows())
                            {
                                if (firstRow)
                                {
                                    foreach (var cell in row.Cells())
                                    {
                                        dt.Columns.Add(cell.Value.ToString());
                                    }

                                    firstRow = false;
                                }

                                dt.Rows.Add();
                                var i = 0;
                                foreach (var cell in row.Cells())
                                {
                                    dt.Rows[dt.Rows.Count - 1][i] = cell.Value.ToString();
                                    i++;
                                }
                            }

                            var pedidos = new List<PedidoExcel>();
                            var cargarPedido = true;
                            for (var i = 0; i < dt.Rows.Count; i++)
                            {
                                for (var j = 0; j < 1; j++)
                                {
                                    if (dt.Rows[i].ItemArray[1].ToString().Trim().IsInt())
                                    {
                                        var item = new PedidoExcel
                                        {
                                            Codigo = dt.Rows[i].ItemArray[0].ToString().Trim().ToUpper(), //Replace(".", "").Trim(),
                                            Cantidad = int.Parse(dt.Rows[i].ItemArray[1].ToString().Replace(".", "").Trim())
                                        };
                                        pedidos.Add(item);
                                        mensaje = "El archivo " + archivoExcel.FileName + " se cargo correctamente";
                                    }
                                    else
                                    {
                                        if (!string.IsNullOrEmpty(dt.Rows[i].ItemArray[1].ToString().Trim()))
                                        {
                                            mensaje = $"La columna B (cantidad) contiene caracteres inválidos ({dt.Rows[i].ItemArray[1].ToString().Trim()}) en la fila {i}, corríjalo y vuelva a intentar.";
                                            cargarPedido = false;
                                            break;
                                        }                                    }
                                }
                            }

TarantoWebCatalogo/TarantoWebCatalogo.Web/Views/Catalogo/CrearPedido.cshtml
@model TarantoWebCatalogo.ViewModels.Pedidos.PedidoCreate

@{
    Layout = "~/Views/Shared/_LayoutUsuarioLogeado.cshtml";
    ViewBag.Title = "Cargar pedido";
}



@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(p => p.Descripcion, new { id = "campoOcultoDescripcion" })
    @Html.HiddenFor(p => p.PrecioUnitario, new { id = "campoOcultoPrecioUnitario" })
    @Html.HiddenFor(p => p.Stock, new { id = "campoOcultoStock" })

    <div class="form-group">
        @Html.LabelFor(model => model.Articulo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-3">
            <div class="twitter-typeahead" style="position: relative; display: inline-block;">
                <input type="text" id="textBoxCodigo" name="Articulo" class="form-control input-catalog" placeholder="Escriba un código" autocomplete="off" spellcheck="false" style="position: relative; vertical-align: top;">
                <div class="tt-menu" style="position: absolute; top: 100%; left: 0px; z-index: 100; display: none;">
                    <div class="tt-dataset">
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-2" id="cargaDeCombosSpin">
            <img src="~/images/preloader.gif" alt="" />
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2">Descripción</label>
        <div class="col-md-10" id="descripcion">
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2">Stock</label>
        <div class="col-md-1" id="stock">
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2">Cantidad</label>
        <div class="col-md-2">
            @Html.EditorFor(model => model.Cantidad, new { htmlAttributes = new { @class = "form-control", id = "cantidad" } })
            @Html.ValidationMessageFor(model => model.Cantidad, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2">Subtotal</label>
        <div class="col-md-10" id="subtotal" style="font-family: Arial">
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" id="btnAgregarArticulo" value="Agregar" class="btn btn-primary" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Volver", MVC.Catalogo.CarritoDeComprasIndex())
</div>


@section scripts
{
    <script> var apiLocalUrl = '@ViewBag.ApiLocalUrl'</script>
    <script>var usuario = '@SeguridadService.UsuarioLogueadoCodigo';</script>
    <script src="~/Scripts/CarritoDeCompras/carritoModel.js"></script>
    <script src="~/Scripts/CarritoDeCompras/carritoManager.js"></script>
    <script src="~/Scripts/CarritoDeCompras/carrito.js?v=3"></script>
}

TarantoWebCatalogo/TarantoWebCatalogo.Web/Views/Catalogo/ListaDePrecios.cshtml
@model List<TarantoWebCatalogo.ViewModels.ListaDePrecios.ListaDePrecio>

@{
    Layout = "~/Views/Shared/_LayoutUsuarioLogeado.cshtml";
    ViewBag.Title = "Lista de precios";
}


<div class="postcontent nobottommargin nobottomborder col_last clearfix content-min-height">

    <div class="heading-block topmargin-sm bottommargin-sm">
        <h3 class="color-azul nott">Lista de precios</h3>
        <span class="linea"></span>
    </div>

    <table class="table table-hover topmargin-sm bottommargin-sm">
        <thead>
            <tr>
                <th colspan="2" style="border-top: none !important;"><b class="small color-rojo"></b></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td><i>@item.NombreArchivo1.ToUpper()</i></td>
                    <td align="right">
                        <a href="https://www.taranto.com.ar/WebAdmin/images/listaDePrecios/@item.Archivo1" class="color-azul" style="margin-right: 10px;">Descargar</a>
                    </td>

                </tr>
                if (item.NombreArchivo2.Length > 0)
                {
                    <tr>
                        <td><i>@item.NombreArchivo2.ToUpper()</i></td>
                        <td align="right">
                            <a href="https://www.taranto.com.ar/WebAdmin/images/listaDePrecios/@item.Archivo2" class="color-azul" style="margin-right: 10px;">Descargar</a>
                        </td>
                    </tr>
                }

                if (item.NombreArchivo3.Length > 0)
                {
                    <tr>
                        <td><i>@item.NombreArchivo3.ToUpper()</i></td>
                        <td align="right">
                            <a href="https://www.taranto.com.ar/WebAdmin/images/listaDePrecios/@item.Archivo3" class="color-azul" style="margin-right: 10px;">Descargar</a>
                        </td>
                    </tr>
                }
            }
        </tbody>
        <thead>
            <tr>
                <th colspan="2" style="border: none !important; padding-bottom: 10px;"></th>
            </tr>
        </thead>
    </table>


    <div class="clearfix bottommargin-sm"></div>

</div>

TarantoWebCatalogo/TarantoWebCatalogo.Web/Views/Catalogo/Ofertas.cshtml
@model List<TarantoWebCatalogo.ViewModels.BoletinLanzamiento.BoletinLanzamiento>

@{
    Layout = "~/Views/Shared/_LayoutUsuarioLogeado.cshtml";
    ViewBag.Title = "Ofertas";
}

<div class="postcontent nobottommargin nobottomborder col_last clearfix content-min-height">

    <div class="heading-block topmargin-sm bottommargin-sm">
        <h3 class="color-azul nott">Boletines / Lanzamientos</h3>
        <span class="linea"></span>
    </div>

    <!-- BOLETINES LANZAMIENTOS -->
    <div id="posts" class="post-grid grid-container clearfix pt-10" data-layout="fitRows" style="position: relative; height: 2600px;">
        
        @foreach (var item in Model)
        {

            <div class="entry entry-releases clearfix" style="position: absolute; left: 0px; top: 10px;">
                <div class="entry-image">
                    <a href="http://200.41.234.45:8991/catalogo/documentoPdf?nombre=@item.Archivo">
                      <div class="img-bg img-1x1 image_fade" style="background-image: url(http://200.41.234.45:8991/catalogo/imagenBoletin?nombre=@item.Imagen); opacity: 1;"></div>
                    </a>
                </div>
                <div class="entry-title">
                    <h2><a href="http://200.41.234.45:8991/catalogo/documentoPdf?nombre=@item.Archivo">@item.TituloEs</a></h2>

                </div>
                <ul class="entry-meta clearfix">
                    <li>
                        <i class="icon-calendar3"></i> @item.FechaCreacion
                    </li>
                </ul>
                <div class="entry-content">
                    <a href="http://200.41.234.45:8991/catalogo/documentoPdf?nombre=@item.Archivo" class="more-link">Ver más</a>
                </div>
            </div>
        }
    </div>


    <div class="clearfix bottommargin-sm"></div>

</div>

TarantoWebCatalogo/TarantoWebCatalogo.Web/Views/Catalogo/PedidoDetalleArticulos.cshtml
@model IEnumerable<TarantoWebCatalogo.ViewModels.Pedidos.PedidoProcesadoItemDetail>

@{
    Layout = "~/Views/Shared/_LayoutUsuarioLogeado.cshtml";
    ViewBag.Title = "DetallePedido";
    var razonSocial = SeguridadService.NombreUsuario;
    var codigoCliente = SeguridadService.UsuarioLogueadoCodigo;
    int contador = 0;
}

<div class="postcontent nobottommargin nobottomborder col_last clearfix content-min-height" style="overflow-x: scroll;">

    <div class="heading-block topmargin-sm bottommargin-sm">
        <h3 class="color-azul nott">Detalle del pedido</h3>
        <span class="linea"></span>
    </div>

    <div class="clearfix"></div>

    <div class="col-xs-12">
        <p class="mt-0 mb-0"><strong class="small">Cliente: @codigoCliente, @razonSocial</strong></p>
    </div>
    <div class="col-sm-4">
        <p class="mt-0 mb-0"><strong class="small">Origen: @ViewBag.Origen</strong></p>
    </div>
    <div class="col-sm-4">
        <p class="mt-0 mb-0"><strong class="small">Fecha: @ViewBag.Fecha</strong></p>
    </div>
    <div class="col-sm-4">
        <p class="mt-0 mb-0"><strong class="small">Nro. Pedido: @ViewBag.IdOracle</strong></p>
    </div>
    <div class="col-sm-4">
        <p class="mt-0 mb-0"><strong class="small">Estado: Enviado correctamente</strong></p>
    </div>
    <div class="col-sm-8">
        <p class="mt-0 mb-0"><strong class="small">Observaciones: @ViewBag.Observacion</strong></p>
    </div>

    <div class="clearfix"></div>

    <table class="table table-hover topmargin-sm bottommargin-sm">
        <thead>
            <tr>
                <th class="tcenter">#</th>
                <th class="tleft">Código</th>
                <th class="tleft hidden">Modelo</th>
                <th class="tleft">Descripción</th>
                <th class="tcenter">Cant.</th>
            </tr>
        </thead>
        <tbody>
        @foreach (var item in Model)
        {
            contador += 1;
            <tr>
                <td class="tcenter">@contador<b class="small"></b></td>
                <td class="tleft"><span class="color-rojo">@item.Articulo</span></td>
                <td class="tleft hidden"><i></i></td>
                <td class="tleft"><i>@item.Descripcion</i></td>
                <td class="tcenter"><b class="small">@item.Cantidad</b></td>
            </tr>
        }
        </tbody>
    </table>



    <div class="clearfix bottommargin"></div>

</div>

TarantoWebCatalogo/TarantoWebCatalogo.Web/Views/Catalogo/PedidoPorExcel.cshtml
@using TarantoWebCatalogo.ViewModels.Pedidos
@model IEnumerable<TarantoWebCatalogo.ViewModels.Pedidos.PedidoDetail>
@{
    Layout = "~/Views/Shared/_LayoutUsuarioLogeado.cshtml";
    ViewBag.Title = "Pedido excel";

}

<div class="postcontent nobottommargin nobottomborder col_last clearfix content-min-height">

    <div class="heading-block topmargin-sm bottommargin-sm">
        <h3 class="color-azul nott">Pedido por excel</h3>
        <span class="linea"></span>
    </div>

    <div class="clearfix bottommargin-sm"></div>
    @if (ViewBag.ProcessStatus == 1)
    {
        <div class="alert bounceIn alert-success alert-dismissible mt-20 " role="alert" id="divPedidoCargadoCorrectamente">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
            <strong>Pedido cargado correctamente..</strong>
        </div>
    }else if (ViewBag.ProcessStatus == 2)
    {
        <div class="alert bounceIn alert-danger alert-dismissible mt-20 " role="alert" id="divPedidoFalloCargaPedido">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
            <strong>El pedido no pudo ser cargado, por favor vuelva a intentarlo</strong>
        </div>
    }

    @if (Model == null)
    {
        <div class="alert alert-warning alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
            Para subir un archivo Excel, cargar en la primera columna el código del artículo y en la segunda la cantidad a pedir. <br>
            Guardar el archivo con cualquier nombre.xlsx <br>
            Máximo 70 líneas. <br>
            <br>
            Ejemplo:
            <img src="~/images/demo_pedido_xls.jpg" class="img-responsive" style="margin-top: 5px;" alt="demo excel">
        </div>
    }


    @using (Html.BeginForm("PedidoPorExcel", "Catalogo", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        if (Model != null)
        {
            @Html.Partial(MVC.Catalogo.Views._ModalPedidoExcelValidado, Model)
        }
        else
        {
            if (ViewBag.Mensaje != null)
            {
                <div class="alert alert-danger alert-dismissible center" role="alert">
                    @Html.Raw(ViewBag.Mensaje)
                </div>
            }
            <input type="file" name="archivoExcel" />
            <br />
            <input id="btnValidarExcel" type="submit" class="btn btn-primary nomargin btn-with-icon" value="Validar excel">
        }

        <img id="validarExcelSpin" src="~/images/preloader.gif" alt="spin" class="hide"/>
    }
</div>


@section scripts
{
    <script>var apiLocalUrl = '@ViewBag.ApiLocalUrl'</script>
    <script>var usuario = '@SeguridadService.UsuarioLogueadoCodigo';</script>
    <script src="~/Scripts/PedidoExcel/pedidoExcel.js"></script>
}

TarantoWebCatalogo/TarantoWebCatalogo.Web/Views/Catalogo/_Catalogo.cshtml
<section id="content">
    <div class="content-wrap">
        <div class="container clearfix">
            
            <div class="col-sm-12 center topmargin-xs bottommargin-xs" id="cargaDeCombosSpinParaResultado">
                <img src="~/images/preloader.gif" alt="" />
            </div>

            <div id="cantidadResultadoBusquedaAvanzada"></div>

            <div id="catalogoCabecera"></div>

            <div id="catalogoDetalle"></div>

            <div id="cuadro"></div>

            <div id="catalogoArticulosRelacionados"></div>

            <div id="paginado"></div>

        </div>
    </div>
</section>

TarantoWebCatalogo/TarantoWebCatalogo.Web/Views/Catalogo/_DetallePedido.cshtml
@model IEnumerable<TarantoWebCatalogo.ViewModels.Pedidos.PedidoDetail>

@{
    const int filasDelResumen = -1;
    var fila = 0;
}

<table class="table table-hover" id="tablaPedido">
    <thead>
        <tr>
            <th>
                Ártículo
            </th>
            <th>
                Descripción
            </th>
            <th id="columnaPrecioUnitario">
                Precio Costo
            </th>
            <th id="columnaPrecioCliente">Precio Venta</th>
            <th>
                @Html.DisplayNameFor(model => model.Stock)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cantidad)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Subtotal)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            @if (item.Total != filasDelResumen)
            {
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td id="filaDescripciontotalEnDetallePedido">Total</td>
                <td id="filaTotalEnDetallePedido">
                    $@Html.DisplayFor(modelItem => item.Total)
                </td>
                <td></td>
            }
            else
            {
                <td>
                    @Html.DisplayFor(modelItem => item.Articulo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Descripcion)
                </td>
                <td class="filaPrecioUnitario" id="precioUnitario-@fila">
                    @Html.DisplayFor(modelItem => item.PrecioUnitario)
                </td>
                <td id="precioCliente-@fila"></td>
                <td>
                    <span class="stock-@item.Stock.ToLower()"></span>
                </td>
                <td id="cantidad-@fila">
                    <a href="#" data-toggle="modal" data-target="#modalEditarCantidadArticulos"
                       data-cantidad="@item.Cantidad" data-articulo="@item.Articulo" data-idpedido="@item.IdPedido">
                        @Html.DisplayFor(modelItem => item.Cantidad, new { id = "cantidad-" + item.Articulo })
                    </a>
                </td>
                <td id="subtotal-@fila">
                    $@Html.DisplayFor(modelItem => item.Subtotal)
                </td>
                <td class="tright">
                    <a href="@Url.Action(MVC.Catalogo.EliminarPedido(item.Articulo, item.IdPedido))">
                        <i class="icon-trash2"></i>
                    </a>
                </td>

                fila++;
            }
        </tr>
        }
    </tbody>
</table>

<div id="page-wrapper">
    <div class="container-fluid">
        @Html.Partial(MVC.Catalogo.Views._ModalEditarCantidadArticulo)
    </div>
</div>

TarantoWebCatalogo/TarantoWebCatalogo.Web/Views/Catalogo/_ModalCotizador.cshtml
@{
    var codigoUsuario = SeguridadService.UsuarioLogueadoCodigo;
    var nombreUsuario = SeguridadService.NombreUsuario;
}

<div id="modalCotizador" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">

            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title">Ajustes</h4>
            </div>
            <div class="modal-body">

                <p class="mt-0 mb-20"><strong class="small">Cliente: @codigoUsuario - @nombreUsuario</strong></p>

                <div id="settings_cart_form_result"></div>
                <form role="form" id="settings_cart_form">
                    <fieldset class="nobottommargin">

                        <label class="label-tnto no-link">Precios calculados para: </label>
                        <div>
                            <input type="radio" name="settings_cart_modo" id="settings_cart_modo_0" class="radio-style" checked="">
                            <label for="settings_cart_modo_0" class="radio-style-2-label radio-small label-tnto2">Carrito de compras</label>
                        </div>
                        <div>
                            <input type="radio" name="settings_cart_modo" id="settings_cart_modo_1" class="radio-style">
                            <label for="settings_cart_modo_1" class="radio-style-2-label radio-small label-tnto2">Cotizador a Clientes</label>
                        </div>

                        <div id="parametros-cotizador-clientes" class="mb-20 div-disabled">

                            <p class="mt-30 mb-10"><strong>Parámetros Cotizador a Cliente final</strong></p>

                            <div class="input-group input-block-level">
                                <label for="descuentoEspecial" class="label-tnto">% Descuento especial</label>
                                <input type="text" name="settings_cart_descuento" id="descuentoEspecial" class="form-control input-block-level modal-form" placeholder="Desc. Taranto"  maxlength="3">
                            </div>
                            <div class="input-group input-block-level">
                                <label for="descuentoProntoPago" class="label-tnto">% Descuento pronto pago</label>
                                <input type="text" name="settings_cart_prontopago" id="descuentoProntoPago" class="form-control input-block-level modal-form" placeholder="Desc. Pronto pago" maxlength="3">
                            </div>
                            <div class="input-group input-block-level">
                                <label for="margen" class="label-tnto">% Márgen</label>
                                <input type="text" name="settings_cart_margen" id="margen" class="form-control input-block-level modal-form" placeholder="Ganancia" maxlength="3">
                            </div>
                            <div class="input-group input-block-level">
                                <label for="iva" class="label-tnto">% IVA (al cliente final)</label>
                                <input type="text" name="settings_cart_iva" id="iva" class="form-control input-block-level modal-form" placeholder="ej: 21" maxlength="2">
                            </div>

                            <div class="clearfix"></div>
                        </div>

                        <button type="button" id="btnCotizadorGuardar" data-loading-text="Cargando..." class="btn btn-danger nomargin btn-block" autocomplete="off">
                            Guardar
                        </button>
                        <input type="submit" class="hidden" value="Guardar">

                    </fieldset>
                </form>
            </div>
        </div>
    </div>
</div>