taranto-panel-admin/Taranto.Panel_Admin.Web/Controllers/BoletinesController.cs
using AutoMapper;
using System;
using System.Collections.Generic;
using System.Net;
using System.Web.Mvc;
using Taranto.Panel_Admin.Data;
using Taranto.Panel_Admin.Data.Repositories.Interfaces;
using Taranto.ViewModels;

namespace Taranto.Panel_Admin.Web.Controllers
{
    [Authorize]
    public class BoletinesController : Controller
    {
        private readonly IBoletinesRepository boletinesRepository;
        private readonly IMapper mapper;
        private readonly IImageFileHandler imageSaver;
        private const string Subfolder = "boletines";

        public BoletinesController(IBoletinesRepository boletinesRepository, IMapper mapper, IImageFileHandler imageSaver)
        {
            this.boletinesRepository = boletinesRepository;
            this.mapper = mapper;
            this.imageSaver = imageSaver;
        }
        // GET: Boletines
        public ActionResult Index()
        {
            var boletines = boletinesRepository.GetAll();
            List<BoletinesVMItem> boletinesItems = new List<BoletinesVMItem>();
            boletines.ForEach(i => boletinesItems.Add(mapper.Map<BoletinesVMItem>(i)));

            return View(new BoletinesVM()
            {
                Items = boletinesItems
            });
        }

        // GET: Boletines/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        public ActionResult Add()
        {
            return View(new BoletinesVMItem(true));
        }

        [HttpPost]
        public ActionResult Add(BoletinesVMItem item)
        {
            if (item.Archivo.File != null)
            {
                item.Archivo.FileName = GenerateFileName(item.Archivo.File.FileName);
                imageSaver.SaveImage(item.Archivo.fileByteArray, item.Archivo.FileName, HttpContext, Subfolder);
            }
            if (item.Imagen.File != null)
            {
                item.Imagen.FileName = GenerateFileName(item.Imagen.File.FileName);
                imageSaver.SaveImage(item.Imagen.fileByteArray, item.Imagen.FileName, HttpContext, Subfolder);
            }

            BoletinLanzamiento entity = mapper.Map<BoletinLanzamiento>(item);
            boletinesRepository.Add(entity);
            return RedirectToAction("Index");
        }

        private string GenerateFileName(string FileName)
        {
            Random random = new Random();

            string newName = random.Next().ToString();
            var extension = System.IO.Path.GetExtension(FileName);

            return newName + extension;
        }
        // GET: Boletines/Edit/5
        public ActionResult Edit(int id)
        {
            if (id == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            BoletinLanzamiento boletin = boletinesRepository.Get(id);

            return View(mapper.Map<BoletinesVMItem>(boletin));
        }

        // POST: Boletines/Edit/5
        [HttpPost, ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(BoletinesVMItem boletin)
        {
            BoletinLanzamiento entity = mapper.Map<BoletinLanzamiento>(boletin);
            BoletinLanzamiento entityFromDB = boletinesRepository.GetAsNoTracking(boletin.Id);

            if (boletin.Imagen.File != null)
            {
                imageSaver.SaveImage(boletin.Imagen.fileByteArray, boletin.Imagen.File.FileName, HttpContext, Subfolder);

            }
            else
            {
                entity.Imagen = entityFromDB.Imagen;
            }

            if (boletin.Archivo.File != null)
            {
                imageSaver.SaveImage(boletin.Archivo.fileByteArray, boletin.Archivo.File.FileName, HttpContext, Subfolder);

            }
            else
            {
                entity.Archivo = entityFromDB.Archivo;
            }

            boletinesRepository.Update(entity);
            return RedirectToAction("Index");
        }

        // GET: Boletines/Delete/5
        public ActionResult Delete(int id)
        {
            boletinesRepository.Delete(id);
            return RedirectToAction("Index");
        }

    }
}

taranto-panel-admin/Taranto.Panel_Admin.Web/Views/Boletines/Add.cshtml
@model Taranto.ViewModels.BoletinesVMItem

@{
    ViewBag.Title = "BOLETINES > NUEVO";
    Layout = "~/Views/Shared/_MultiLanguageLayout.cshtml";
}

<div class="mt-30 mt-sm-40 text-center">
    <h4 class="text-uppercase letter-spacing-1">@ViewBag.Title</h4>
</div>

@using (Html.BeginForm("Add", "Boletines", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="tab-content">
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.EditorFor(model => model.FechaCreacion)

    @Html.EditorFor(model => model.Titulo)

    @Html.EditorFor(model => model.Imagen, new { Id = "Imagen" })
    @Html.EditorFor(model => model.Archivo, new { Label = "Archivo Adjunto", Id = "Archivo" })


</div>
    <hr class="mt-40">
    <div class="form-group">
        <button type="submit" id="btnSlider" data-loading-text="Cargando..." class="btn btn-block btn-backend" autocomplete="off">
            Guardar
        </button>
        <input type="submit" class="hidden" value="Add">
    </div>
}

<script>
    $(function () {
        
    });
</script>

taranto-panel-admin/Taranto.Panel_Admin.Web/Views/Boletines/Edit.cshtml
@model Taranto.ViewModels.BoletinesVMItem

@{
    ViewBag.Title = "BOLETINES > EDICION";
    Layout = "~/Views/Shared/_MultiLanguageLayout.cshtml";
}

<div class="mt-30 mt-sm-40 text-center">
    <h4 class="text-uppercase letter-spacing-1">@ViewBag.Title</h4>
</div>

@using (Html.BeginForm("Edit", "Boletines", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="tab-content">
    @Html.EditorFor(model => model.FechaCreacion)

    @Html.EditorFor(model => model.Titulo)

    @Html.EditorFor(model => model.Imagen, new { Id = "Imagen" })
    @Html.EditorFor(model => model.Archivo, new { Label = "Archivo Adjunto", Id = "Archivo" })

</div>
    <hr class="mt-40">
    <div class="form-group">
        <button type="submit" id="btnSlider" data-loading-text="Cargando..." class="btn btn-block btn-backend" autocomplete="off">
            Guardar
        </button>
        <input type="submit" class="hidden" value="Guardar">
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

taranto-panel-admin/Taranto.Panel_Admin.Web/Views/Boletines/Index.cshtml
@model  Taranto.ViewModels.BoletinesVM
@{
    ViewBag.Title = "Boletines";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@ViewBag.Message
<section class="container clearfix">

    <div class="row mt-30">
        <div class="col-sm-8 col-sm-offset-2">


            <a href="boletines/add" class="btn btn-default">Cargar nuevo <span aria-hidden="true" class="glyphicon glyphicon-plus"></span></a>
            <div class="clearfix"></div>


            <div class="mt-30 mt-sm-40 text-center">
                <h3 class="text-uppercase letter-spacing-1">@ViewBag.Title</h3>
            </div>
            @{
                var request = HttpContext.Current.Request;
                var appUrl = HttpRuntime.AppDomainAppVirtualPath;
                var baseUrl = string.Format("{0}://{1}{2}", request.Url.Scheme, request.Url.Authority, appUrl);

                if (Model == null) { return; }
                foreach (var item in Model.Items)
                {
                        <div id="article-3" class="article mt-30">
                            @{ 
                                var imagenUrl = string.Concat(baseUrl, item.Imagen.ToString());
                            }
                            <div class="article-image" style="background-image: url(@imagenUrl)"></div>
                            <div class="article-content">
                                <h4 class="font-regular">@item.Titulo</h4>

                            </div>
                            <div class="article-content">
                                <h4 class="font-regular">@item.FechaCreacion.ToString("dd MMM yyyy")</h4>

                            </div>
                            <div class="clearfix"></div>
                            
                            <a href="@Url.Action("Edit", "Boletines", new { Id = item.Id }, Request.Url.Scheme)" class="btn btn-default mt-10">Editar <span aria-hidden="true" class="glyphicon glyphicon-pencil"></span></a>
                            <a href="javascript:if(confirm('Seguro quieres borrar?')){parent.location='Boletines/delete?id=@item.Id';};" class="btn btn-default mt-10">Eliminar <span aria-hidden="true" class="glyphicon glyphicon-remove"></span></a>
                        </div>
                }
            }

        </div>
    </div>

</section>