taranto-panel-admin/Taranto.Panel_Admin.Web/Controllers/InfoController.cs
using AutoMapper;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Taranto.Panel_Admin.Data;
using Taranto.Panel_Admin.Data.Repositories.Interfaces;
using Taranto.ViewModels;

namespace Taranto.Panel_Admin.Web.Controllers
{
    [Authorize]
    public class InfoController : Controller
    {
        private readonly IInfoRepository infoRepository;
        private readonly IMapper mapper;
        private readonly List<string> tituloInstitucional;

        public InfoController(IInfoRepository infoRepository, IMapper mapper)
        {
            this.infoRepository = infoRepository;
            this.mapper = mapper;
        }


        // GET: Info
        public ActionResult Index()
        {
            var info = infoRepository.GetAll();
            List<InfoVMItem> infoItems = new List<InfoVMItem>();
            info.ForEach(i => infoItems.Add(mapper.Map<InfoVMItem>(i)));

            return View(new InfoVM()
            {
                Items = infoItems
            });
        }

        // GET: Info/Details/5
        public ActionResult Details(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            InfoVMItem institucional = mapper.Map<InfoVMItem>(infoRepository.Get(id));
            if (institucional == null)
            {
                return HttpNotFound();
            }
            return View(institucional);
        }

        // GET: Info/Edit/1
        public ActionResult Edit(int id)
        {
            if (id == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            
            Info info = infoRepository.Get(id);

            if (info == null)
            {
                return HttpNotFound();
            }
            return View(mapper.Map<InfoVMItem>(info));
        }

        // POST: Info/Edit/1
        [HttpPost, ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(InfoVMItem info)
        {
            if (ModelState.IsValid)
            {
                infoRepository.Update(mapper.Map<Info>(info));
                return RedirectToAction("Index");
            }
            return View(info);
        }

        // GET: Info/Create
        public ActionResult Add()
        {
            return View(new InfoVMItem(true));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Add(InfoVMItem info)
        {
            if (ModelState.IsValid)
            {

                infoRepository.Add(mapper.Map<Info>(info));

                return RedirectToAction("Index");
            }

            return View(info);
        }

        // POST: Info/Delete/5
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            infoRepository.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

taranto-panel-admin/Taranto.Panel_Admin.Web/Controllers/LogoutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Configuration;
using System.Web.Mvc;
using System.Web.Security;

namespace Taranto.Panel_Admin.Web.Controllers
{
    public class LogoutController :  Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            FormsAuthentication.SignOut();
            Session.Abandon();

            // clear authentication cookie
            HttpCookie cookie1 = new HttpCookie(FormsAuthentication.FormsCookieName, "");
            cookie1.Expires = DateTime.Now.AddYears(-1);
            Response.Cookies.Add(cookie1);

            // clear session cookie (not necessary for your current problem but i would recommend you do it anyway)
            SessionStateSection sessionStateSection = (SessionStateSection)WebConfigurationManager.GetSection("system.web/sessionState");
            HttpCookie cookie2 = new HttpCookie(sessionStateSection.CookieName, "");
            cookie2.Expires = DateTime.Now.AddYears(-1);
            Response.Cookies.Add(cookie2);
            return RedirectToAction("Index", "Login");
        }
    }
}

taranto-panel-admin/Taranto.Panel_Admin.Web/Controllers/OfertasController.cs
using AutoMapper;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data.Entity.Validation;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Configuration;
using System.Web.Mvc;
using Taranto.Panel_Admin.Data;
using Taranto.Panel_Admin.Data.Repositories.Interfaces;
using Taranto.ViewModels;

namespace Taranto.Panel_Admin.Web.Controllers
{
    [Authorize]
    public class OfertasController : Controller
    {
        private readonly IOfertasRepository ofertasRepository;
        private readonly IMapper mapper;
        private readonly IImageFileHandler imageSaver;
        private const string Subfolder = "ofertas";

        public OfertasController(IOfertasRepository ofertasRepository, IMapper mapper, IImageFileHandler imageSaver)
        {
            this.ofertasRepository = ofertasRepository;
            this.mapper = mapper;
            this.imageSaver = imageSaver;
        }
        // GET: Ofertas
        public ActionResult Index()
        {
            var ofertas = ofertasRepository.GetAll();
            var ofertaItems = new List<OfertaViewModelItem>();
            ofertas.ForEach(p => ofertaItems.Add(mapper.Map<OfertaViewModelItem>(p)));

            return View(new OfertaViewModel()
            {
                Items = ofertaItems
            });
        }


        // GET: Ofertas/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Ofertas/Add
        [HttpGet]
        public async Task<ActionResult> Add()
        {
            var vm = new OfertaViewModel(true)
            {
                ClasesCliente = await GetClaseCliente(),
                Clientes = await GetClientes(),
                CuposCliente = await GetCupoCliente()
            };



            return View(vm);
        }

        private async Task<IEnumerable<OfertaCuposCliente>> GetCupoCliente()
        {
            var apiUrl = WebConfigurationManager.AppSettings["ApiUrl"];
            var url = $"{apiUrl}distribuidores/cupos";

            IEnumerable<OfertaCuposCliente> result;
            using (var client = new HttpClient())
            {
                var content = await client.GetStringAsync(url);
                result = JsonConvert.DeserializeObject<List<OfertaCuposCliente>>(content);
            }
            return result;

        }

        private async Task<IEnumerable<OfertaCliente>> GetClientes()
        {
            var apiUrl = WebConfigurationManager.AppSettings["ApiUrl"];
            var url = $"{apiUrl}distribuidores/sucursales";
            IEnumerable<OfertaCliente> result;
            using (var client = new HttpClient())
            {

                var content = await client.GetStringAsync(url);
                result = JsonConvert.DeserializeObject<List<OfertaCliente>>(content);
            }
            return result;
        }

        private static async Task<IEnumerable<OfertaClaseCliente>> GetClaseCliente()
        {
            var apiUrl = WebConfigurationManager.AppSettings["ApiUrl"];
            var url = $"{apiUrl}distribuidores/tipos";

            IEnumerable<OfertaClaseCliente> result;
            using (var client = new HttpClient())
            {
                var content = await client.GetStringAsync(url);
                result = JsonConvert.DeserializeObject<List<OfertaClaseCliente>>(content);
            }
            return result;
        }

        // POST: Ofertas/Add
        [HttpPost]
        public ActionResult Add(OfertaViewModelItem oferta)
        {
            try
            {
                if(oferta.ArchivoAdjunto.File != null)
                {
                    imageSaver.SaveImage(oferta.ArchivoAdjunto.fileByteArray, oferta.ArchivoAdjunto.File.FileName, HttpContext, Subfolder);
                }
                if (oferta.Image.File != null)
                {
                    imageSaver.SaveImage(oferta.Image.fileByteArray, oferta.Image.File.FileName, HttpContext, Subfolder);
                }

                Oferta entity = mapper.Map<Oferta>(oferta);
                var newId = ofertasRepository.Add(entity);
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch (DbEntityValidationException ex)
            {
                return View();
            }
        }

        // GET: Ofertas/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            var vm = new OfertaViewModel(true);
            var item = ofertasRepository.Get(id);
            vm.ClasesCliente = await GetClaseCliente();
            vm.Clientes = await GetClientes();
            vm.CuposCliente = await GetCupoCliente();
            var claseSelected = item.Clase.Split(';').ToList();
            var clienteSelected = item.Excluir.Split(';').ToList();
            var cupoSelected = item.Cuota.Split(';').ToList();


            
            foreach (var claseCliente in vm.ClasesCliente)
            {
                if (claseSelected.Contains(claseCliente.CustomerNumber))
                {
                    claseCliente.Selected = true;
                }
            }
            foreach (var cliente in vm.Clientes)
            {
                if (clienteSelected.Contains(cliente.CodigoCliente))
                {
                    cliente.Selected = true;
                }
            }
            foreach (var cupo in vm.CuposCliente)
            {
                if (cupoSelected.Contains(cupo.Descripcion))
                {
                    cupo.Selected = true;
                }
            }

            vm.Items = new List<OfertaViewModelItem>() { mapper.Map<OfertaViewModelItem>(item) };
            
            return View(vm);
        }

        // POST: Ofertas/Edit/5
        [HttpPost, ValidateInput(false)]
        public ActionResult Edit(OfertaViewModelItem editItem)
        {
            try
            {
                Oferta entity = mapper.Map<Oferta>(editItem);
                Oferta entityFromDB = ofertasRepository.GetAsNoTracking(editItem.Id);

                if (!string.IsNullOrWhiteSpace(editItem.existingPath) && editItem.Image.File != null)
                {
                    imageSaver.SaveImage(editItem.Image.fileByteArray, editItem.Image.File.FileName, HttpContext, Subfolder);

                }
                else
                {
                    entity.Imagen = entityFromDB.Imagen;
                }

                if (editItem.ArchivoAdjunto.File != null)
                {
                    imageSaver.SaveImage(editItem.ArchivoAdjunto.fileByteArray, editItem.ArchivoAdjunto.File.FileName, HttpContext, Subfolder);

                }
                else
                {
                    entity.Archivo = entityFromDB.Archivo;
                }

                ofertasRepository.Update(entity);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return View();
            }
        }
        
        public ActionResult Delete(int id)
        {
            try
            {
                // TODO: Add delete logic here
                ofertasRepository.Delete(id);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

taranto-panel-admin/Taranto.Panel_Admin.Web/Controllers/RRHHController.cs
using AutoMapper;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Taranto.Panel_Admin.Data;
using Taranto.Panel_Admin.Data.Repositories.Interfaces;
using Taranto.ViewModels;

namespace Taranto.Panel_Admin.Web.Controllers
{
    [Authorize]
    public class RRHHController : Controller
    {
        private readonly IRRHHRepository rrhhRepository;
        private readonly IMapper mapper;

        public RRHHController(IRRHHRepository rrhhRepository, IMapper mapper)
        {
            this.rrhhRepository = rrhhRepository;
            this.mapper = mapper;
        }


        // GET: Info
        public ActionResult Index()
        {
            var rrhh = rrhhRepository.GetAll();
            List<RRHHBusquedaVMItem> busquedasItems = new List<RRHHBusquedaVMItem>();
            rrhh.ForEach(i => busquedasItems.Add(mapper.Map<RRHHBusquedaVMItem>(i)));

            return View(new RRHHBusquedaVM()
            {
                Items = busquedasItems
            });
        }

        // GET: Info/Details/5
        public ActionResult Details(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RRHHBusquedaVMItem rrhh = mapper.Map<RRHHBusquedaVMItem>(rrhhRepository.Get(id));
            if (rrhh == null)
            {
                return HttpNotFound();
            }
            return View(rrhh);
        }

        // GET: Info/Edit/1
        public ActionResult Edit(int id)
        {
            if (id == 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RRHHBusquedaVMItem rrhh = mapper.Map<RRHHBusquedaVMItem>(rrhhRepository.Get(id));
            
            if (rrhh == null)
            {
                return HttpNotFound();
            }
            return View(rrhh);
        }

        // POST: Info/Edit/1
        [HttpPost, ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(RRHHBusquedaVMItem rrhh)
        {
            if (ModelState.IsValid)
            {
                rrhhRepository.Update(mapper.Map<RecursosHumanosBusqueda>(rrhh));
                return RedirectToAction("Index");
            }
            return View(rrhh);
        }

        // GET: Info/Create
        public ActionResult Add()
        {
            return View(new RRHHBusquedaVMItem(true));
        }

        [HttpPost, ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult Add(RRHHBusquedaVMItem rrhh)
        {
            if (ModelState.IsValid)
            {
                rrhhRepository.Add(mapper.Map<RecursosHumanosBusqueda>(rrhh));

                return RedirectToAction("Index");
            }

            return View(rrhh);
        }

        // POST: Info/Delete/5
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            rrhhRepository.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

taranto-panel-admin/Taranto.Panel_Admin.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Taranto - Panel Admin</title>



    @Scripts.Render("~/bundles/jquery")
    
    @Styles.Render("~/Content/css/datepicker.min.css")

    @Styles.Render("~/Content/css/summernote.css")


    @Styles.Render("~/Content/css/backend-main-1.2.min.css")
    @Styles.Render("~/Content/css/basic-1.2.min.css")
    @Scripts.Render("~/bundles/modernizr")

    <link href="~/Content/css/datepicker.min.css" rel="stylesheet" />
    <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
    <script src="~/Content/js/jquery.datepicker.min.js"></script>

    <link href="~/Content/css/bootstrap-select.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
</head>
<body>
    <!-- LOADING -->
    <div id="loading" style="display: none;">
        <div class="css3-spinner">
            <div class="css3-spinner-bounce1"></div>
            <div class="css3-spinner-bounce2"></div>
            <div class="css3-spinner-bounce3"></div>
        </div>
    </div>

    <!-- NAV -->

    <nav class="navbar navbar-fixed-top">
        <section class="container clearfix">

            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-main" aria-expanded="false">
                    <span class="sr-only">Menu</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="/home" class="navbar-brand">
                    <h1>Taranto</h1>
                </a>
            </div>
            <div class="collapse navbar-collapse" id="navbar-main">
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Administración <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="@Url.Action("Index", "SliderHome")">Slider Home</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="@Url.Action("Index", "Categorias")">Categorías</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="@Url.Action("Index", "Productos")">Productos</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="@Url.Action("Index", "Novedades")">Novedades</a></li>
                            <li><a href="@Url.Action("Index", "CategoriasNovedades")">Novedades &gt; Categorías</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="@Url.Action("Index", "Institucionales")">Secciones institucionales</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="@Url.Action("Index", "Info")">Sub páginas de información</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="@Url.Action("Index", "RRHH")">RRHH &gt; Búsquedas Activas</a></li>
                            <li role="separator" class="divider"></li>
                            @*<li><a href="@Url.Action("Index", "Revista")">Revista Juntando Partes</a></li>*@
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">General <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="@Url.Action("Index", "Consultas")">Consultas</a></li>
                            <li><a href="@Url.Action("Index", "Suscriptos")">Suscriptos Newsletter</a></li>
                            <li><a href="@Url.Action("Index", "RRHHPostulaciones")">CV RRHH / Postulaciones</a></li>
                            <li><a href="@Url.Action("Index", "NuevosDistribuidores")">Nuevos distribuidores</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="@Url.Action("Index", "Estadisticas")">Google Analytics</a></li>
                            <li><a href="@Url.Action("Index", "Estadisticas")">Add This</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Extranet <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="@Url.Action("Index", "CtaCteComprobantes")">Cuenta Corriente &gt; Comprobantes</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="@Url.Action("Index", "SolicitudEditarDatos")">Solicitud de editar datos / Cargar fotos</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="@Url.Action("Index", "Sugerencias")">Sugerencias</a></li>
                            <li><a href="@Url.Action("Index", "SugerenciasCategorias")">Sugerencias &gt; Categorías</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="@Url.Action("Index", "Reclamos")">Reclamos</a></li>
                            <li><a href="@Url.Action("Index", "ReclamosCategorias")">Reclamos &gt; Categorías</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="@Url.Action("Index", "Boletines")">Boletines / Lanzamientos</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="@Url.Action("Index", "Ofertas")">Ofertas</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="@Url.Action("Index", "ListaDePrecios")">Lista de precios</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="@Url.Action("Index", "DatosCuentasBancarias")">Datos de cuentas bancarias</a></li>
                        </ul>
                    </li>
                    <li class="logout"><a href="@Url.Action("Index", "Logout")" title="Logout"><span class="glyphicon glyphicon-off txt-red big" aria-hidden="true"></span><strong>Logout</strong></a></li>
                </ul>
            </div>

        </section>
    </nav>

    <!-- HEADER -->
    <!-- FOOTER -->
    <footer>
        <section class="container clearfix">

            <div class="row pt-30 pb-30">
                <div class="col-xs-12">

                </div>
            </div>

        </section>
    </footer>
    <div class="container body-content">
        @RenderBody()

        <footer>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")


    @RenderSection("scripts", required: false)


    <script src="https://code.jquery.com/jquery-2.1.4.min.js" integrity="sha256-8WqyJLuWKRBVhxXIL1jBDD7SDxU936oZkCnxQbWwJVw=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>


    <script src="~/Content/js/plugins/jquery.bootstrap.js"></script>
    <script src="~/Content/js/components/bs-select.js"></script>
    <script src="~/Content/js/components/bootstrap-filestyle.min.js"></script>
    <script src="~/Content/js/bootstrap-select.min.js"></script>
    <script src="~/Content/js/summernote.min.js"></script>
    <script src="~/Content/js/lang/summernote-es-ES.js"></script>
    <script src="~/Content/js/backend-valid-forms-1.3.min.js"></script>
    <script src="~/Content/js/backend-settings-1.3.min.js"></script>
    <script src="~/Content/js/main.js"></script>
    <link href="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.12/summernote.css" rel="stylesheet">
    <script src="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.12/summernote.js"></script>
</body>
</html>

taranto-panel-admin/Taranto.Panel_Admin.Web/Views/Shared/_MultiLanguageLayout.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Scripts.Render("~/bundles/jquery")
<ul class="nav nav-tabs tabs-idioma">
    <li>
        <a href="#tab-br" data-toggle="tab" class="small text-center">Português</a>
    </li>
    <li>
        <a href="#tab-en" data-toggle="tab" class="small text-center">English</a>
    </li>
    <li class="active">
        <a href="#tab-es" id="spanish-tab" data-toggle="tab" class="small text-center">Español</a>
    </li>
</ul>
@RenderBody()

<script>
    $(function () {
        $("#spanish-tab").click();
    })
</script>